function Neuro = RunTask(Params,Neuro)
% Explains the task to the subject, and serves as a reminder for pausing
% and quitting the experiment (w/o killing matlab or something)
switch Params.ControlMode,
    case 1, % Mouse Position
        Instructions = [...
        '\n\nMouse Position Control\n\n'...
        '\nAt any time, you can press ''p'' to briefly pause the task.'...
        '\n\nPress the ''Space Bar'' to begin!' ];
    case 2, % Mouse Velocity
        Instructions = [...
        '\n\nMouse Velocity Control\n\n'...
        '\nAt any time, you can press ''p'' to briefly pause the task.'...
        '\n\nPress the ''Space Bar'' to begin!' ];
    case 3, % Kalman Filter Velocity Decoder
        Instructions = [...
        '\n\nKalman Brain Control\n\n'...
        '\nAt any time, you can press ''p'' to briefly pause the task.'...
        '\n\nPress the ''Space Bar'' to begin!' ];
    
    % Initialize Kalman Filter
    Neuro.KF = InitializeKF(Params.imagined_datadir);
end

InstructionScreen(Params,Instructions);
Neuro = RunLoop(Params,Neuro);

end % RunTask